# Generated by Django 4.2.4 on 2023-08-11 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Назвнаие блога')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Описание блога')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда создан блог')),
                ('uodated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего обновления')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(db_index=True, max_length=50, verbose_name='Автор')),
                ('body', models.TextField(verbose_name='комментарий')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда написанн комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=20, verbose_name='Назвнаие тега')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='Никнейм')),
                ('is_admin', models.BooleanField(choices=[(True, ' Администратор'), (False, 'Не админимтратор')], db_index=True, default='False', null=True, verbose_name='Статус пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Назвнаие заголовка')),
                ('body', models.TextField(verbose_name='Текст поста')),
                ('is_published', models.BooleanField(choices=[(True, 'Опубликован'), (False, 'не опубликован')], db_index=True, default='False', null=True, verbose_name='Статус публикации поста')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Когда создан пост')),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='application.blog', verbose_name='Автор поста')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='application.tag', verbose_name='Теги')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_name='owners', to='application.user', verbose_name='Автор(ы)'),
        ),
    ]
