# Generated by Django 4.2.4 on 2023-08-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
