# Generated by Django 4.2.4 on 2023-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='application.post', verbose_name='Лайкнутые посты'),
        ),
    ]
