# Generated by Django 4.2.4 on 2023-08-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_uodated_at_blog_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserName',
        ),
    ]
