# Generated by Django 4.2.4 on 2023-08-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserName',
            new_name='User',
        ),
    ]
