# Generated by Django 4.2.4 on 2023-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_username_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Назвнаие тега'),
        ),
    ]
