# Generated by Django 4.2.4 on 2023-08-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_blog_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='application.post', verbose_name='Посты блога'),
            preserve_default=False,
        ),
    ]
