# Generated by Django 4.2.4 on 2023-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='authors',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='application.user', verbose_name='Автор(ы)'),
        ),
    ]
