# Generated by Django 4.2.4 on 2023-08-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='posts',
            new_name='post',
        ),
    ]
