# Generated by Django 4.2.4 on 2023-08-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_blog_author_blog_authors_user_liked_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
