# Generated by Django 4.2.4 on 2023-08-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_rename_posts_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='post',
            new_name='posts',
        ),
    ]
