# Generated by Django 4.2.4 on 2023-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_post_blog_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='application.post', verbose_name='Посты блога'),
        ),
    ]
