# Generated by Django 4.2.4 on 2023-08-18 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0011_remove_blog_posts_blog_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_post',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
